// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwsniadpkctbjvmmsdjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3c25pYWRwa2N0Ymp2bW1zZGpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM4MDA3NjcsImV4cCI6MjA4OTM3Njc2N30.yS-Q8S_mTJPsbBWn6hk25iwb0aRWqKRc9S4ofiyLrw0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});